### ISSUE TITLE
Add admin security and management features

### ISSUE THREAD

**Issue by intelligentnode** [intelligentnode/IntelliServer#21]
When releasing the image to the docker hub we ignore the .env file which eliminates the saved keys.

We want to add services to update the api default key and the admin default default key from the admin api:
https://github.com/intelligentnode/IntelliServer/blob/main/intelliserver/api/routes/admin.js

**Expected changes**:
- Suggest a suitable approach to persist (store)  the api values.
- Update `router.put('/api-auth-flag', ..)` to persist (store) the received value from the API. This should not contradict with current functionality, so if the user did not update the flag keep reading the .evn or default value. But if the user sets the flag the priority for the persisted (stored) value.
- Add a function to update the API key and store the new key securely.
- Add a function to update the admin key and store the new key securely.
- Add a function to reset the admin settings to default and read the .env values.

**Comment by Barqawiz** [comment]
This is resolved with simple approach to send the key when running the docker image. Keeping the key management outside the scope of the server, controlled based on each user environment.
