### ISSUE TITLE
Add image to text functionality

### ISSUE THREAD

**Issue by intelligentnode** [intelligentnode/IntelliServer#45]
Add an OCR functionality to read text from images using Google and AWS API.

**Steps:**
- Create a folder called ocr with index file.
- Add AWS function to convert images to text (aws_ocr).
- Add Google function to convert images to text (goog_ocr).

**Authentication:**
- AWS receive AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY
- Google receive OAuth token.

**Validation:**
- Add postman collection with testing details.
- Add swagger documentation and test it works.

**Comment by pushoo-sharma** [comment]
@intelligentnode Question
In the auth section you mentioned,

**Authentication**:
AWS receive AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY
Google receives an OAuth token.

So do we need to proxy it and use our credentials or take it from API? 
since for OAuth, it can expire but AWS cred would still remain

**Comment by intelligentnode** [comment]
- For AWS, store the values in .env with priority for the keys in the api call.
- For Google, read the OAuth token from the api call only.

**Comment by pushoo-sharma** [comment]
2 Points @intelligentnode 
- We can GOOGLE_APPLICATION_CREDENTIALS for Google Vision instead of the OAuth token
- On URL vs Local,
we can use both of them 
    1. for Local, we are using Multar to get buffer data from the image
    2. for URL, we first have to download the image and then pass its buffer to functions [we may create a middleware to do so

**Comment by intelligentnode** [comment]
Great let’s move with your suggestion for the google vision. This way we can support the key form .env and the API call, which is aligned with existing code.

And about the image, let’s support both upload options to give flexibility for the user. You can control this either using different parameter flag or different wrapper function.

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by pushoo-sharma** [comment]
Sounds good, can you also pass the credentials for both AWS and GCP @intelligentnode

**Comment by pushoo-sharma** [comment]
Pushed, middleware that handles URL/file to upload based on req body key 
Can you send credentials so that I can cross-check if it's working correctly or not @intelligentnode?

**Comment by pushoo-sharma** [comment]
AWS Rekognition has been tested and verified via API, doc has been added as well
